nodes:
  - name: tchat_websocket
    protocol: websocket
    address: ws://localhost:5500
  - name: capture_demo
    protocol: artnet
links:
  - input: tchat_websocket
    conditions:
      - type: "contains"
        value: "hey"
    actions:
      - output: lights_osc
        action:
          address: "/lights/on"
          args:
            - type: "int32"
              value: 0
            - type: "int32"
              value: 255
            - type: "int32"
              value: 0
            - type: "float32"
              value: 3.1416
            - type: "string"
              value: "Hello, OSC!"
